### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mayurbagga** [Web3-Agent/Web3Agent#20]
- [ ] solve this error while use the prompts it is not generating form  
![image](https://github.com/Web3-Agent/Web3Agent/assets/16322269/33f4a180-bd00-4972-87a9-9461290b9c76)

- [ ] implement functionality to perform swap with multichain functionality
- [ ] implement new functionality for smart contract to deploy from userthe ccount instead of our account
- [ ] make separate pages and components for DEFI, DEPLOY CONTRACTS & SEND TRANSACTIONS, currently these 3 options are same

**Comment by mayurbagga** [comment]
5th task added
